Implement Custom Permission Popover for Camera and Audio Access
kaali001/varta pull request #23
Opened 2024-10-26 18:49 UTC by Suman-Jyoti-Phukan

## Description

This update introduces a custom permission popover to request user permission for camera and audio access. The component is designed to streamline the user experience by managing permissions within the active session and minimizing redundant prompts. Initially , I thought it would take me a couple hours but I was wrong. It became more complicated but at the end it worked out fine. And sorry , I had to PR with my master branch as I was too focus on developing it.

Fixes #21 

## Changes

List the changes done to fix a bug or introducing a new feature.

I had to apply many chances and introduce new states,effects that hadles various situations. There were few challenges while creating this component. 

- Introduced multiple components to manage and display the user’s current permission status, along with prompts to request permissions as needed.
- Ensured cross-browser compatibility for consistent behavior across different environments.
- Implemented multiple useEffect hooks and state variables to handle various permission and event states reliably.
- The if conditions are a bit to hard to explain without actually running the program. So, I have left multiple comments. 

## How to test

Simply open the development server and hit the join button at https://localhost:3000/chat, you will notice a custom permission component.

## Checklist:

- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my code
- [Y] I have commented my code, particularly in hard-to-understand areas
- [N] I have made corresponding changes to the documentation
- [Y] My changes generate no new warnings
- [Y] I have added tests that prove my fix is effective or that my feature works

2024-10-27 06:41 UTC, kaali001 commented
@Suman-Jyoti-Phukan Its nice PR,   But its need few modifications, make changes as given below -

1. Make a new folder named as `media_permission` for your new files created in component folder.

2. Use  this in the UI of pop up card - 
    - color pallet - #d53b84,#fa546b, #c14020, #f1633d
    - Fonts - Cinzel, Quattrocento, Ultine Extended Demi

3. Fix the issue - on clicking the chat button the chat getting started even if the popup for permission is there, Actually by clicking on chat button it directly makes chat active and call ` room` component even without permission. You can solve this by adding a step in between that if the all permission is allowed then it makes chat active `true` .  

4. Instead of adding many functions on the `chat.tsx` file you can create a new file in `media_permission` for handling all this and keep  only components call on `chat.tsx` file ,  as it's a inappropriate that you crated 4 new files and still defining many function in `chat.tsx` .

2024-10-27 12:17 UTC, Suman-Jyoti-Phukan commented
Hey , thanks for the update. I'll make the appropriate changes you asked. And for the point 3, it was already directly making the chat active and call  room component even without permission. I had noticed it but decided not to fix it. However , It can be fixed with few changes.

2024-10-27 12:23 UTC, Suman-Jyoti-Phukan commented
Hey can clarify on thing. You want a media_permission inside the components folder or in the src folder?

2024-10-27 15:01 UTC, Suman-Jyoti-Phukan commented
Hey , I have made the changes you have asked. Please check it out and leave me a review. Thank you.

2024-10-27 16:30 UTC, kaali001 commented on client/src/pages/Room.tsx
@Suman-Jyoti-Phukan , This file doesn't require any changes, Please let me know if you faced any issue with in this file, as I go through this file it seems you made changes in the text inline, I will remove this file from PR. Waiting for your response.

2024-10-27 16:51 UTC, kaali001 requested changes
@Suman-Jyoti-Phukan , This PR resolved all existing issue, just remove the `Room.tsx` file  from PR as it does not need to be change , And change the file type of  `mediaPermissions.ts` file to `.tsx` . Then its ready to be merge.

2024-10-27 17:23 UTC, Suman-Jyoti-Phukan commented
I have done the changes. Can you check it now?

2024-10-27 19:19 UTC, kaali001 commented
@Suman-Jyoti-Phukan , You removed all the codes of  `Room.tsx` file ,  that's why Vercel — Deployment has failed. 
You don't need to remove all codes from file you just have to use original code of this file. you can get original code from my master branch.

2024-10-27 19:23 UTC, Suman-Jyoti-Phukan commented
Never mind. I thought you told me to delete the file. I will update it and re commit it.

2024-10-28 06:44 UTC, Suman-Jyoti-Phukan commented
Hey @kaali001 , I have made the changes. Do have a look at it. Thank you.

2024-10-28 14:23 UTC, kaali001 approved these changes

2024-10-28 14:24 UTC, merged

2024-10-28 14:28 UTC, kaali001 commented
@Suman-Jyoti-Phukan , It was a nice contribution. I have merged the PR by making the `room.tsx` file as it was still not updated by you.    Now  can you  open a new issue for fixing the ui of the permission popup card as it looks kind of ugly.

2024-10-28 15:00 UTC, Suman-Jyoti-Phukan commented
Thanks. It was great collaborating with you. I will work on it as soon as possible. However, it would be great if you can provide some insight on how to style it.